services:
  frontend:
    image: aatishbh/frontend:${IMAGE_TAG}
    restart: always
  backend:
    image: aatishbh/backend:${IMAGE_TAG}
    restart: always
    env_file:
      - './server/.env'
  nginx:
    image: aatishbh/nginx:${IMAGE_TAG}
    restart: always
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend