version: '3.8'

services:
  frontend:
    image: aatishbh/frontend:1.0.0
    build:
      context: ./client
    expose:
      - "3000"
  backend:
    image: aatishbh/backend:1.0.0
    build:
      context: ./server
    env_file:
      - './server/.env'
    expose:
      - "3001"
  nginx:
    image: aatishbh/nginx:1.0.0
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend